const BRL = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const state={tab:'dashboard',detail:null};
const base=window.ELO_DATA;
let orders=JSON.parse(localStorage.getItem('elo_orders')||'null')||base.orders;
let clients=JSON.parse(localStorage.getItem('elo_clients')||'null')||base.clients;
let history=JSON.parse(localStorage.getItem('elo_history')||'[]');
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function save(){localStorage.setItem('elo_orders',JSON.stringify(orders));localStorage.setItem('elo_clients',JSON.stringify(clients));}
function norm(s){return (s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function monthName(m){return ['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'][Number(m)]||m}
function saldo(o){return Math.max(0,Number(o.total||0)-Number(o.recebido||0));}
function payStatus(o){let s=saldo(o); if(s<=.01)return 'Pago'; if(Number(o.recebido||0)>0)return 'Parcial'; return 'Falta pagar'}
function sync(o){o.saldo=+saldo(o).toFixed(2); o.pagamento=payStatus(o); return o}
orders=orders.map(sync); save();
function filters(){return{year:$('#fYear').value,month:$('#fMonth').value,client:$('#fClient').value,pay:$('#fPay').value,prod:$('#fProd').value,cat:$('#fCat').value,min:$('#fMin').value,max:$('#fMax').value}}
function filtered(){const f=filters();return orders.filter(o=>(!f.year||String(o.year)==f.year)&&(!f.month||String(o.month)==f.month)&&(!f.client||o.cliente_norm==f.client)&&(!f.pay||payStatus(o)==f.pay)&&(!f.prod||o.producao==f.prod)&&(!f.cat||o.categoria==f.cat)&&(!f.min||Number(o.total)>=Number(f.min))&&(!f.max||Number(o.total)<=Number(f.max))).map(sync)}
function sum(arr,k='total'){return arr.reduce((a,o)=>a+Number(o[k]||0),0)}
function group(arr,key){return arr.reduce((a,o)=>{let k=typeof key==='function'?key(o):o[key];(a[k]??=[]).push(o);return a},{})}
function setVal(id,val){const el=$('#'+id); if(el) el.value = val ?? '';}
function initFilters(){
 const current = ['fYear','fMonth','fClient','fPay','fProd','fCat','fMin','fMax'].reduce((a,id)=>(a[id]=$('#'+id)?.value||'',a),{});
 let years=[...new Set(orders.map(o=>o.year).filter(Boolean))].sort();
 $('#fYear').innerHTML='<option value="">Todos</option>'+years.map(y=>`<option value="${y}">${y}</option>`).join('');
 $('#fMonth').innerHTML='<option value="">Todos</option>'+Array.from({length:12},(_,i)=>i+1).map(m=>`<option value="${m}">${String(m).padStart(2,'0')} - ${monthName(m)}</option>`).join('');
 let cls=[...new Map(clients.map(c=>[c.id,c])).values()].sort((a,b)=>a.nome.localeCompare(b.nome));
 $('#fClient').innerHTML='<option value="">Todos</option>'+cls.map(c=>`<option value="${c.id}">${c.nome}</option>`).join('');
 let cats=[...new Set(orders.map(o=>o.categoria||'Outros'))].sort();
 $('#fCat').innerHTML='<option value="">Todas</option>'+cats.map(c=>`<option value="${c}">${c}</option>`).join('');
 $('#oClient').innerHTML=cls.map(c=>`<option value="${c.id}">${c.nome}</option>`).join('');
 $('#oCat').innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join('')+`<option value="Outros">Outros</option>`;
 Object.entries(current).forEach(([id,val])=>{ if(val) setVal(id,val); });
}
function render(){initFilters(); $('#title').textContent={dashboard:'Dashboard',pedidos:'Pedidos',financeiro:'Financeiro',producao:'Produção',clientes:'Clientes',agenda:'Reativação'}[state.tab]; $$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab==state.tab)); const data=filtered(); const views={dashboard, pedidos, financeiro, producao, clientesView, agenda}; $('#app').innerHTML=views[state.tab](data); bind();}
function kpis(data){let due=data.filter(o=>saldo(o)>0), fazer=data.filter(o=>o.producao=='Por fazer'), pronto=data.filter(o=>o.producao=='Pronto'||o.producao=='Há entregar'); return `<div class="cards"><div class="card"><h3>Faturamento filtrado</h3><div class="num">${BRL.format(sum(data))}</div></div><div class="card"><h3>Recebido</h3><div class="num green">${BRL.format(sum(data,'recebido'))}</div></div><div class="card"><h3>Saldo em aberto</h3><div class="num red">${BRL.format(sum(due,'saldo'))}</div></div><div class="card"><h3>Pedidos</h3><div class="num">${data.length}</div></div><div class="card"><h3>Por produzir</h3><div class="num amber">${fazer.length}</div></div><div class="card"><h3>Pronto / há entregar</h3><div class="num amber">${pronto.length}</div></div><div class="card"><h3>Clientes únicos</h3><div class="num">${new Set(data.map(o=>o.cliente_norm)).size}</div></div><div class="card"><h3>Ticket médio</h3><div class="num">${BRL.format(data.length?sum(data)/data.length:0)}</div></div></div>`}
function dashboard(data){let byMonth=Object.entries(group(data,o=>`${o.year}-${String(o.month).padStart(2,'0')}`)).sort().map(([m,arr])=>`<tr><td>${m}</td><td>${BRL.format(sum(arr))}</td><td>${arr.length}</td><td>${BRL.format(sum(arr,'saldo'))}</td></tr>`).join(''); let top=Object.entries(group(data,'cliente_norm')).map(([k,arr])=>({k,n:arr[0].cliente,v:sum(arr),s:sum(arr,'saldo'),q:arr.length})).sort((a,b)=>b.v-a.v).slice(0,10).map(x=>`<tr><td><span class="click client-detail" data-client="${x.k}">${x.n}</span></td><td>${BRL.format(x.v)}</td><td>${x.q}</td><td>${BRL.format(x.s)}</td></tr>`).join(''); return kpis(data)+`<div class="split"><div class="panel"><h2>Resumo por mês</h2><table><thead><tr><th>Mês</th><th>Faturamento</th><th>Pedidos</th><th>Saldo</th></tr></thead><tbody>${byMonth}</tbody></table></div><div class="panel"><h2>Top clientes no filtro</h2><table><thead><tr><th>Cliente</th><th>Total</th><th>Pedidos</th><th>Aberto</th></tr></thead><tbody>${top}</tbody></table></div></div>`}
function tableOrders(arr){return `<table><thead><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Total</th><th>Recebido</th><th>Saldo</th><th>Pag.</th><th>Produção</th><th>Ações</th></tr></thead><tbody>${arr.map(o=>`<tr><td>${o.date||String(o.month).padStart(2,'0')+'/'+o.year}</td><td><span class="click client-detail" data-client="${o.cliente_norm}">${o.cliente}</span></td><td>${o.produto}</td><td>${BRL.format(o.total)}</td><td>${BRL.format(o.recebido)}</td><td>${BRL.format(saldo(o))}</td><td><span class="tag ${payStatus(o)=='Pago'?'green':payStatus(o)=='Parcial'?'amber':'red'}">${payStatus(o)}</span></td><td><span class="tag">${o.producao}</span></td><td class="actions"><button class="mini edit" data-id="${o.id}">Editar</button><button class="mini dup" data-id="${o.id}">Duplicar</button><button class="mini receive" data-id="${o.id}">Receber</button><button class="mini pay" data-id="${o.id}">Pago</button><button class="mini status" data-id="${o.id}" data-s="Pronto">Pronto</button><button class="mini status" data-id="${o.id}" data-s="Entregue">Entregue</button><button class="mini del" data-id="${o.id}">Excluir</button></td></tr>`).join('')}</tbody></table>`}
function pedidos(data){return kpis(data)+`<div class="panel"><div class="searchbar"><input id="quick" placeholder="Pesquisar cliente, produto, valor..."></div>${tableOrders(data)}</div>`}
function financeiro(data){let debt=data.filter(o=>saldo(o)>0); let rows=Object.entries(group(debt,'cliente_norm')).map(([k,arr])=>({k,n:arr[0].cliente,ttl:sum(arr),rec:sum(arr,'recebido'),s:sum(arr,'saldo'),q:arr.length,arr})).sort((a,b)=>b.s-a.s).map(x=>`<tr><td><span class="click debt-detail" data-client="${x.k}">${x.n}</span></td><td>${x.q}</td><td>${BRL.format(x.ttl)}</td><td>${BRL.format(x.rec)}</td><td><b class="red">${BRL.format(x.s)}</b></td></tr><tr class="details" id="debt-${x.k}" style="display:none"><td colspan="5"><div class="drawer">${tableOrders(x.arr)}</div></td></tr>`).join(''); return kpis(data)+`<div class="panel"><h2>Clientes devedores agrupados</h2><p>Este total respeita os filtros de ano, mês, cliente, categoria e valor.</p><table><thead><tr><th>Cliente</th><th>Itens</th><th>Total vendido</th><th>Recebido</th><th>Saldo aberto</th></tr></thead><tbody>${rows||'<tr><td colspan="5">Nenhum saldo aberto no filtro.</td></tr>'}</tbody></table></div>`}
function producao(data){let fazer=data.filter(o=>o.producao=='Por fazer'); let pronto=data.filter(o=>o.producao=='Pronto'||o.producao=='Há entregar'); let entregar=data.filter(o=>o.entrega=='Há entregar'||o.producao=='Há entregar'); return kpis(data)+`<div class="split"><div class="panel"><h2>Falta produzir</h2>${tableOrders(fazer)}</div><div class="panel"><h2>Pronto / há entregar</h2>${tableOrders([...pronto,...entregar].filter((v,i,a)=>a.findIndex(x=>x.id==v.id)==i))}</div></div>`}
function clientesView(data){let rows=Object.entries(group(data,'cliente_norm')).map(([k,arr])=>({k,n:arr[0].cliente,total:sum(arr),saldo:sum(arr,'saldo'),ped:arr.length,last:arr.map(o=>`${o.year}-${String(o.month).padStart(2,'0')}`).sort().at(-1),cats:[...new Set(arr.map(o=>o.categoria))].slice(0,3).join(', ')})).sort((a,b)=>b.total-a.total).map(x=>`<tr><td><span class="click client-detail" data-client="${x.k}">${x.n}</span></td><td>${x.ped}</td><td>${BRL.format(x.total)}</td><td>${BRL.format(x.saldo)}</td><td>${x.last}</td><td>${x.cats}</td><td><button class="mini edit-client" data-client="${x.k}">Editar cadastro</button></td></tr>`).join(''); return kpis(data)+`<div class="panel"><div class="rowhead"><h2>Clientes cadastrados e consolidados</h2><button class="mini new-client">+ Novo cliente</button></div><p>Clique no cliente para abrir itens, datas e histórico. Use “Editar cadastro” para registrar apelidos e evitar duplicidade.</p><table><thead><tr><th>Cliente</th><th>Pedidos</th><th>Faturamento</th><th>Aberto</th><th>Última compra</th><th>Categorias</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function agenda(data){let all=Object.entries(group(orders,'cliente_norm')).map(([k,arr])=>({k,n:arr[0].cliente,total:sum(arr),saldo:sum(arr,'saldo'),last:arr.map(o=>new Date(o.year,o.month-1,1)).sort((a,b)=>b-a)[0],cats:[...new Set(arr.map(o=>o.categoria))]})); let today=new Date(2026,6,3); let rows=all.map(x=>({...x,dias:Math.floor((today-x.last)/(86400000))})).filter(x=>x.dias>60||x.saldo>0).sort((a,b)=>(b.saldo-a.saldo)||(b.dias-a.dias)).slice(0,80).map(x=>`<tr><td><span class="click client-detail" data-client="${x.k}">${x.n}</span></td><td>${BRL.format(x.total)}</td><td>${BRL.format(x.saldo)}</td><td>${x.dias} dias</td><td>${x.saldo>0?'Cobrar saldo em aberto':'Reativar compra'}</td><td><button class="mini msg" data-client="${x.k}">Gerar mensagem</button></td></tr>`).join(''); return `<div class="panel"><h2>Lista de reativação e cobrança</h2><table><thead><tr><th>Cliente</th><th>Total histórico</th><th>Aberto</th><th>Sem comprar</th><th>Ação</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div id="msgBox"></div>`}
function bind(){
 $$('.nav').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()}); ['fYear','fMonth','fClient','fPay','fProd','fCat','fMin','fMax'].forEach(id=>$('#'+id).oninput=render); $('#clearFilters').onclick=()=>{$$('.filters select,.filters input').forEach(e=>e.value='');render()};
 $$('.edit').forEach(b=>b.onclick=()=>openOrder(b.dataset.id)); $$('.dup').forEach(b=>b.onclick=()=>duplicate(b.dataset.id)); $$('.del').forEach(b=>b.onclick=()=>del(b.dataset.id)); $$('.receive').forEach(b=>b.onclick=()=>addPayment(b.dataset.id)); $$('.pay').forEach(b=>b.onclick=()=>{let o=orders.find(x=>x.id==b.dataset.id); if(!o) return; o.recebido=o.total;sync(o);hist(o.id,'Marcado como pago');save();render()}); $$('.status').forEach(b=>b.onclick=()=>{let o=orders.find(x=>x.id==b.dataset.id); if(!o) return; o.producao=b.dataset.s;if(b.dataset.s=='Entregue'){o.entrega='Entregue'} hist(o.id,'Status: '+b.dataset.s);save();render()});
 $$('.new-client').forEach(e=>e.onclick=()=>openClient()); $$('.debt-detail').forEach(e=>e.onclick=()=>{let r=$('#debt-'+e.dataset.client); if(r)r.style.display=r.style.display=='none'?'table-row':'none'}); $$('.client-detail').forEach(e=>e.onclick=()=>clientDetail(e.dataset.client)); $$('.edit-client').forEach(e=>e.onclick=()=>openClient(e.dataset.client)); $$('.msg').forEach(e=>e.onclick=()=>message(e.dataset.client)); let q=$('#quick'); if(q)q.oninput=()=>{let val=norm(q.value); let arr=filtered().filter(o=>norm([o.cliente,o.produto,o.total,o.date].join(' ')).includes(val)); q.closest('.panel').querySelector('table').outerHTML=tableOrders(arr); bind()}
}
function clientDetail(cn){let arr=filtered().filter(o=>o.cliente_norm==cn); if(!arr.length) arr=orders.filter(o=>o.cliente_norm==cn); let c=arr[0]; $('#app').insertAdjacentHTML('afterbegin',`<div class="panel"><h2>${c.cliente}</h2><p>Total no filtro: <b>${BRL.format(sum(arr))}</b> | Recebido: <b>${BRL.format(sum(arr,'recebido'))}</b> | Aberto: <b class="red">${BRL.format(sum(arr,'saldo'))}</b> | Pedidos: ${arr.length}</p>${tableOrders(arr)}</div>`); window.scrollTo({top:0,behavior:'smooth'}); bind()}
function message(cn){let arr=orders.filter(o=>o.cliente_norm==cn), c=arr[0]; let aberto=sum(arr,'saldo'); let msg=aberto>0?`Oi, ${c.cliente}! Tudo bem? Estou conferindo nossos lançamentos e consta um saldo em aberto de ${BRL.format(aberto)}. Pode verificar para mim, por gentileza?`:`Oi, ${c.cliente}! Tudo bem? Estava revisando nosso histórico de pedidos e lembrei de vocês. Temos novidades em brindes personalizados, uniformes e kits corporativos. Posso te enviar algumas ideias para a empresa?`; $('#msgBox').innerHTML=`<div class="panel"><h2>Mensagem sugerida</h2><textarea style="width:100%;height:120px">${msg}</textarea></div>`}
function openOrder(id){let o=id?orders.find(x=>x.id==id):null; $('#modalTitle').textContent=o?'Editar pedido':'Novo pedido'; $('#oId').value=o?.id||''; $('#oDate').value=o?.date||''; $('#oClient').value=o?.cliente_norm||clients[0]?.id; $('#oProduct').value=o?.produto||''; $('#oCat').value=o?.categoria||'Outros'; $('#oQty').value=o?.qty||1; $('#oTotal').value=o?.total||0; $('#oReceived').value=o?.recebido||0; $('#oPay').value=o?.pagamento||'Falta pagar'; $('#oProd').value=o?.producao||'Por fazer'; $('#oDelivery').value=o?.entrega||'Pendente'; $('#oOrigin').value=o?.origem||'Manual'; $('#oObs').value=o?.obs||''; $('#orderModal').showModal()}
function addPayment(id){
 let o=orders.find(x=>x.id==id); if(!o) return;
 let atual=Number(o.recebido||0), aberto=saldo(o);
 let txt=prompt(`Valor recebido agora de ${o.cliente}:\nSaldo aberto: ${BRL.format(aberto)}\nRecebido atual: ${BRL.format(atual)}`, aberto.toFixed(2).replace('.',','));
 if(txt===null) return;
 let valor=Number(String(txt).replace(/\./g,'').replace(',','.'));
 if(isNaN(valor) || valor<0){ alert('Valor inválido.'); return; }
 o.recebido = +(atual + valor).toFixed(2);
 if(o.recebido > Number(o.total||0)) o.recebido = Number(o.total||0);
 sync(o); hist(o.id, 'Pagamento lançado: '+BRL.format(valor)); save(); render();
}
function duplicate(id){let o={...orders.find(x=>x.id==id)}; o.id='M-'+Date.now(); o.date=''; o.recebido=0; sync(o); orders.unshift(o); hist(o.id,'Pedido duplicado'); save(); render()}
function del(id){if(confirm('Excluir este pedido?')){orders=orders.filter(o=>o.id!=id); hist(id,'Pedido excluído'); save(); render()}}
function hist(id,text){history.push({id,text,at:new Date().toLocaleString('pt-BR')}); localStorage.setItem('elo_history',JSON.stringify(history))}
$('#newOrderBtn').onclick=()=>openOrder(); $('#saveOrder').onclick=(ev)=>{ev.preventDefault(); let cn=$('#oClient').value, c=clients.find(x=>x.id==cn)||{nome:'Sem cliente'}; let id=$('#oId').value||'M-'+Date.now(); let dt=$('#oDate').value; let mm=(dt.match(/\d{2}\/(\d{2})\/(\d{4})/)||[]); let old=orders.find(x=>x.id==id); let o={id,year:mm?Number(mm[2]):new Date().getFullYear(),month:mm?Number(mm[1]):new Date().getMonth()+1,date:dt,cliente:c.nome,cliente_norm:cn,produto:$('#oProduct').value,categoria:$('#oCat').value,qty:Number($('#oQty').value||1),unit:0,total:Number($('#oTotal').value||0),recebido:Number($('#oReceived').value||0),pagamento:$('#oPay').value,producao:$('#oProd').value,entrega:$('#oDelivery').value,origem:$('#oOrigin').value,obs:$('#oObs').value}; sync(o); if(old) Object.assign(old,o); else orders.unshift(o); hist(id,old?'Pedido editado':'Pedido criado'); save(); $('#orderModal').close(); render()};
function openClient(cn){let c=clients.find(x=>x.id==cn)||{id:'',nome:'',aliases:[],telefone:'',email:'',obs:''}; $('#cId').value=c.id; $('#cName').value=c.nome; $('#cAliases').value=(c.aliases||[]).join(', '); $('#cPhone').value=c.telefone||''; $('#cEmail').value=c.email||''; $('#cObs').value=c.obs||''; $('#clientModal').showModal()}
$('#saveClient').onclick=(ev)=>{ev.preventDefault();let id=$('#cId').value||norm($('#cName').value);let c=clients.find(x=>x.id==id); if(!c){c={id,nome:'',aliases:[],tipo:'Cliente',telefone:'',email:'',obs:'',ativo:true};clients.push(c)} c.nome=$('#cName').value;c.aliases=$('#cAliases').value.split(',').map(x=>x.trim()).filter(Boolean);c.telefone=$('#cPhone').value;c.email=$('#cEmail').value;c.obs=$('#cObs').value;orders.filter(o=>o.cliente_norm==id).forEach(o=>o.cliente=c.nome); save(); $('#clientModal').close(); render()}
$('#resetData').onclick=()=>{if(confirm('Restaurar base original? Isso apaga edições locais.')){localStorage.clear();location.reload()}}
render();
