'use client';
import { useMemo, useState } from 'react';

type Pedido = {id:number; data:string; cliente:string; produto:string; quantidade:number; valor:number; recebido:number; pagamento:'Aberto'|'Parcial'|'Pago'; producao:'Por fazer'|'Em produção'|'Pronto'|'Entregue'; categoria:string; obs?:string};
type Cliente = {nome:string; aliases:string[]; telefone?:string; tipo:'B2B'|'Final'|'Marketplace'};

const clientesBase: Cliente[] = [
 {nome:'Rauber', aliases:['Bruna Rauber'], tipo:'B2B'},
 {nome:'FEBRACIS', aliases:['Fabricio','Fabrício','Febracis'], tipo:'B2B'},
 {nome:'Água e Luz', aliases:['Agua e Luz','crediario agua e luz'], tipo:'B2B'},
 {nome:'Alison', aliases:[], tipo:'B2B'},
 {nome:'Eletrocar', aliases:[], tipo:'B2B'},
 {nome:'Sabrina Lumiere', aliases:['sabrina lumiere','Sabrina'], tipo:'B2B'},
 {nome:'La Salle', aliases:['la salle'], tipo:'B2B'},
 {nome:'Cleo', aliases:[], tipo:'B2B'},
 {nome:'Dani', aliases:[], tipo:'B2B'},
 {nome:'Franciele', aliases:['Francielli'], tipo:'Final'},
];

const pedidosBase: Pedido[] = [
 {id:1001,data:'2026-06-08',cliente:'Água e Luz',produto:'Camiseta',quantidade:120,valor:4380,recebido:0,pagamento:'Aberto',producao:'Entregue',categoria:'Uniformes'},
 {id:1002,data:'2026-06-15',cliente:'Eletrocar',produto:'Caneta metal',quantidade:300,valor:1770,recebido:0,pagamento:'Aberto',producao:'Pronto',categoria:'Brindes'},
 {id:1003,data:'2026-06-15',cliente:'Eletrocar',produto:'Chaveiro',quantidade:300,valor:1470,recebido:0,pagamento:'Aberto',producao:'Pronto',categoria:'Brindes'},
 {id:1004,data:'2026-06-15',cliente:'Eletrocar',produto:'Vira mate',quantidade:500,valor:2400,recebido:0,pagamento:'Aberto',producao:'Pronto',categoria:'Brindes'},
 {id:1005,data:'2026-06-22',cliente:'La Salle',produto:'Copo cuia',quantidade:290,valor:6525,recebido:5171,pagamento:'Parcial',producao:'Por fazer',categoria:'Copos'},
 {id:1006,data:'2026-06-30',cliente:'Alison',produto:'Caneca de porcelana',quantidade:100,valor:1800,recebido:0,pagamento:'Aberto',producao:'Por fazer',categoria:'Canecas'},
 {id:1007,data:'2026-06-12',cliente:'Cleo',produto:'Kit viagem',quantidade:100,valor:1250,recebido:1250,pagamento:'Pago',producao:'Por fazer',categoria:'Brindes'},
 {id:1008,data:'2026-06-09',cliente:'Franciele',produto:'Camiseta PV',quantidade:14,valor:910,recebido:452,pagamento:'Parcial',producao:'Por fazer',categoria:'Uniformes'},
 {id:1009,data:'2026-06-22',cliente:'Dani',produto:'Bandeira',quantidade:1,valor:79.90,recebido:79.90,pagamento:'Pago',producao:'Por fazer',categoria:'Gráfica'},
 {id:1010,data:'2026-06-22',cliente:'Dani',produto:'Avental infantil',quantidade:8,valor:383.20,recebido:383.20,pagamento:'Pago',producao:'Por fazer',categoria:'Uniformes'},
 {id:1011,data:'2026-06-26',cliente:'Rauber',produto:'Kit pipoca',quantidade:10,valor:279,recebido:0,pagamento:'Aberto',producao:'Pronto',categoria:'Brindes'},
 {id:1012,data:'2026-05-11',cliente:'Rauber',produto:'Vira mate',quantidade:500,valor:1750,recebido:1750,pagamento:'Pago',producao:'Entregue',categoria:'Brindes'},
 {id:1013,data:'2026-03-12',cliente:'Alison',produto:'Caneca de porcelana',quantidade:150,valor:2700,recebido:2700,pagamento:'Pago',producao:'Entregue',categoria:'Canecas'},
 {id:1014,data:'2026-01-06',cliente:'FEBRACIS',produto:'Caneta + Moleskine',quantidade:25,valor:572.50,recebido:0,pagamento:'Aberto',producao:'Por fazer',categoria:'Brindes'},
];

const brl = (v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function Page(){
 const [tab,setTab]=useState('Dashboard');
 const [clientes,setClientes]=useState(clientesBase);
 const [pedidos,setPedidos]=useState(pedidosBase);
 const [filtro,setFiltro]=useState({mes:'todos',cliente:'todos',pagamento:'todos',producao:'todos',categoria:'todos'});
 const [edit,setEdit]=useState<Pedido|null>(null);
 const [clienteModal,setClienteModal]=useState<Cliente|null>(null);
 const filtrados=useMemo(()=>pedidos.filter(p=>{
  const mes=p.data.slice(0,7);
  return (filtro.mes==='todos'||mes===filtro.mes)&&(filtro.cliente==='todos'||p.cliente===filtro.cliente)&&(filtro.pagamento==='todos'||p.pagamento===filtro.pagamento)&&(filtro.producao==='todos'||p.producao===filtro.producao)&&(filtro.categoria==='todos'||p.categoria===filtro.categoria)
 }),[pedidos,filtro]);
 const total=filtrados.reduce((s,p)=>s+p.valor,0), recebido=filtrados.reduce((s,p)=>s+p.recebido,0), saldo=total-recebido;
 const porFazer=filtrados.filter(p=>p.producao==='Por fazer').length;
 const devedores=Object.values(filtrados.filter(p=>p.valor-p.recebido>0).reduce((acc:any,p)=>{acc[p.cliente]??={cliente:p.cliente,total:0,recebido:0,saldo:0,itens:[]}; acc[p.cliente].total+=p.valor; acc[p.cliente].recebido+=p.recebido; acc[p.cliente].saldo+=p.valor-p.recebido; acc[p.cliente].itens.push(p); return acc;},{}));
 const salvarPedido=(p:Pedido)=>{setPedidos(prev=>prev.some(x=>x.id===p.id)?prev.map(x=>x.id===p.id?p:x):[{...p,id:Date.now()},...prev]);setEdit(null)};
 const receber=(p:Pedido)=>{const val=Number(prompt('Valor recebido:', String((p.valor-p.recebido).toFixed(2)))||0); if(val>0){const rec=Math.min(p.valor,p.recebido+val); setPedidos(prev=>prev.map(x=>x.id===p.id?{...x,recebido:rec,pagamento:rec>=x.valor?'Pago':'Parcial'}:x))}};
 const marcarPago=(p:Pedido)=>setPedidos(prev=>prev.map(x=>x.id===p.id?{...x,recebido:x.valor,pagamento:'Pago'}:x));
 const excluir=(p:Pedido)=>{if(confirm('Excluir este pedido?')) setPedidos(prev=>prev.filter(x=>x.id!==p.id))};
 const duplicar=(p:Pedido)=>setEdit({...p,id:Date.now(),data:new Date().toISOString().slice(0,10)});
 const atualizarStatus=(p:Pedido,producao:Pedido['producao'])=>setPedidos(prev=>prev.map(x=>x.id===p.id?{...x,producao}:x));
 return <div className="app"><aside className="side"><div className="brand">ELO+<small>BRINDES</small></div><div className="nav">{['Dashboard','Pedidos','Financeiro','Produção','Clientes','CRM'].map(n=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}>{n}</button>)}</div></aside><main className="main"><div className="top"><div className="title"><h1>{tab}</h1><p>ERP comercial, financeiro e operacional da Elo+</p></div><button className="btn" onClick={()=>setEdit({id:Date.now(),data:new Date().toISOString().slice(0,10),cliente:clientes[0].nome,produto:'',quantidade:1,valor:0,recebido:0,pagamento:'Aberto',producao:'Por fazer',categoria:'Brindes'})}>+ Novo pedido</button></div><Filtros filtro={filtro} setFiltro={setFiltro} clientes={clientes} pedidos={pedidos}/>{tab==='Dashboard'&&<><div className="grid cards"><Card t="Faturamento filtrado" v={brl(total)}/><Card t="Recebido" v={brl(recebido)}/><Card t="Saldo a receber" v={brl(saldo)}/><Card t="Por produzir" v={`${porFazer} pedidos`}/></div><section className="grid two" style={{marginTop:16}}><div className="card"><h3>Maiores devedores</h3><Devedores devedores={devedores} setClienteModal={setClienteModal}/></div><div className="card"><h3>Produção em aberto</h3>{filtrados.filter(p=>p.producao!=='Entregue').slice(0,8).map(p=><p key={p.id}><b>{p.cliente}</b> — {p.produto} <span className="badge amber">{p.producao}</span></p>)}</div></section></>}{tab==='Pedidos'&&<Tabela pedidos={filtrados} setEdit={setEdit} receber={receber} marcarPago={marcarPago} excluir={excluir} duplicar={duplicar} atualizarStatus={atualizarStatus}/>} {tab==='Financeiro'&&<div className="card"><h3>Devedores agrupados por cliente</h3><Devedores devedores={devedores} setClienteModal={setClienteModal}/></div>} {tab==='Produção'&&<Producao pedidos={filtrados} atualizarStatus={atualizarStatus}/>} {tab==='Clientes'&&<Clientes clientes={clientes} pedidos={pedidos} setClientes={setClientes}/>} {tab==='CRM'&&<div className="card"><h3>Reativação</h3><p>Próximo passo: score de recompra, agenda de visitas e mensagens automáticas por cliente.</p></div>}</main>{edit&&<PedidoModal pedido={edit} clientes={clientes} salvar={salvarPedido} fechar={()=>setEdit(null)}/>} {clienteModal&&<ClienteDetalhe nome={clienteModal.nome} itens={(clienteModal as any).itens} fechar={()=>setClienteModal(null)}/>}</div>
}
function Card({t,v}:{t:string;v:string}){return <div className="card"><div className="label">{t}</div><div className="metric">{v}</div></div>}
function Filtros({filtro,setFiltro,clientes,pedidos}:any){const meses=[...new Set(pedidos.map((p:Pedido)=>p.data.slice(0,7)))].sort();const cats=[...new Set(pedidos.map((p:Pedido)=>p.categoria))].sort();return <div className="filters"><select value={filtro.mes} onChange={e=>setFiltro({...filtro,mes:e.target.value})}><option value="todos">Todos os meses</option>{meses.map((m:string)=><option key={m}>{m}</option>)}</select><select value={filtro.cliente} onChange={e=>setFiltro({...filtro,cliente:e.target.value})}><option value="todos">Todos clientes</option>{clientes.map((c:Cliente)=><option key={c.nome}>{c.nome}</option>)}</select><select value={filtro.pagamento} onChange={e=>setFiltro({...filtro,pagamento:e.target.value})}><option value="todos">Pagamento</option><option>Aberto</option><option>Parcial</option><option>Pago</option></select><select value={filtro.producao} onChange={e=>setFiltro({...filtro,producao:e.target.value})}><option value="todos">Produção</option><option>Por fazer</option><option>Em produção</option><option>Pronto</option><option>Entregue</option></select><select value={filtro.categoria} onChange={e=>setFiltro({...filtro,categoria:e.target.value})}><option value="todos">Categoria</option>{cats.map((c:string)=><option key={c}>{c}</option>)}</select><button className="btn secondary" onClick={()=>setFiltro({mes:'todos',cliente:'todos',pagamento:'todos',producao:'todos',categoria:'todos'})}>Limpar</button></div>}
function Tabela({pedidos,setEdit,receber,marcarPago,excluir,duplicar,atualizarStatus}:any){return <div className="card"><table className="table"><thead><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Total</th><th>Recebido</th><th>Saldo</th><th>Pagamento</th><th>Produção</th><th>Ações</th></tr></thead><tbody>{pedidos.map((p:Pedido)=><tr key={p.id}><td>{p.data}</td><td>{p.cliente}</td><td>{p.produto}</td><td>{brl(p.valor)}</td><td>{brl(p.recebido)}</td><td>{brl(p.valor-p.recebido)}</td><td><span className={`badge ${p.pagamento==='Pago'?'green':p.pagamento==='Parcial'?'amber':'red'}`}>{p.pagamento}</span></td><td><select value={p.producao} onChange={e=>atualizarStatus(p,e.target.value)}><option>Por fazer</option><option>Em produção</option><option>Pronto</option><option>Entregue</option></select></td><td><div className="actions"><button className="btn secondary" onClick={()=>setEdit(p)}>Editar</button><button className="btn secondary" onClick={()=>duplicar(p)}>Duplicar</button><button className="btn green" onClick={()=>receber(p)}>Receber</button><button className="btn green" onClick={()=>marcarPago(p)}>Pago</button><button className="btn red" onClick={()=>excluir(p)}>Excluir</button></div></td></tr>)}</tbody></table></div>}
function Devedores({devedores,setClienteModal}:any){return <table className="table"><thead><tr><th>Cliente</th><th>Total</th><th>Recebido</th><th>Saldo</th><th>Itens</th></tr></thead><tbody>{devedores.map((d:any)=><tr key={d.cliente}><td><button className="btn secondary" onClick={()=>setClienteModal(d)}>{d.cliente}</button></td><td>{brl(d.total)}</td><td>{brl(d.recebido)}</td><td><b>{brl(d.saldo)}</b></td><td>{d.itens.length}</td></tr>)}</tbody></table>}
function Producao({pedidos,atualizarStatus}:any){return <div className="grid two"><div className="card"><h3>Por fazer / Em produção</h3>{pedidos.filter((p:Pedido)=>['Por fazer','Em produção'].includes(p.producao)).map((p:Pedido)=><p key={p.id}><b>{p.cliente}</b> — {p.produto} <button className="btn secondary" onClick={()=>atualizarStatus(p,'Pronto')}>Marcar pronto</button></p>)}</div><div className="card"><h3>Pronto / Há entregar</h3>{pedidos.filter((p:Pedido)=>p.producao==='Pronto').map((p:Pedido)=><p key={p.id}><b>{p.cliente}</b> — {p.produto} <button className="btn green" onClick={()=>atualizarStatus(p,'Entregue')}>Entregue</button></p>)}</div></div>}
function Clientes({clientes,pedidos,setClientes}:any){const [novo,setNovo]=useState(''); return <div className="card"><h3>Cadastro oficial de clientes</h3><div className="filters"><input placeholder="Novo cliente" value={novo} onChange={e=>setNovo(e.target.value)}/><button className="btn" onClick={()=>{if(novo.trim()){setClientes([...clientes,{nome:novo.trim(),aliases:[],tipo:'B2B'}]);setNovo('')}}}>Cadastrar</button></div><table className="table"><thead><tr><th>Cliente</th><th>Apelidos</th><th>Pedidos</th><th>Total comprado</th></tr></thead><tbody>{clientes.map((c:Cliente)=>{const ps=pedidos.filter((p:Pedido)=>p.cliente===c.nome);return <tr key={c.nome}><td>{c.nome}</td><td>{c.aliases.join(', ')||'-'}</td><td>{ps.length}</td><td>{brl(ps.reduce((s:number,p:Pedido)=>s+p.valor,0))}</td></tr>})}</tbody></table></div>}
function PedidoModal({pedido,clientes,salvar,fechar}:any){const [p,setP]=useState(pedido); return <div className="modal"><div className="modal-box"><h2>Pedido</h2><div className="form"><label>Data<input type="date" value={p.data} onChange={e=>setP({...p,data:e.target.value})}/></label><label>Cliente<select value={p.cliente} onChange={e=>setP({...p,cliente:e.target.value})}>{clientes.map((c:Cliente)=><option key={c.nome}>{c.nome}</option>)}</select></label><label>Produto<input value={p.produto} onChange={e=>setP({...p,produto:e.target.value})}/></label><label>Categoria<input value={p.categoria} onChange={e=>setP({...p,categoria:e.target.value})}/></label><label>Quantidade<input type="number" value={p.quantidade} onChange={e=>setP({...p,quantidade:Number(e.target.value)})}/></label><label>Valor total<input type="number" value={p.valor} onChange={e=>setP({...p,valor:Number(e.target.value)})}/></label><label>Recebido<input type="number" value={p.recebido} onChange={e=>{const recebido=Number(e.target.value);setP({...p,recebido,pagamento:recebido>=p.valor?'Pago':recebido>0?'Parcial':'Aberto'})}}/></label><label>Produção<select value={p.producao} onChange={e=>setP({...p,producao:e.target.value})}><option>Por fazer</option><option>Em produção</option><option>Pronto</option><option>Entregue</option></select></label><label className="full">Observações<textarea value={p.obs||''} onChange={e=>setP({...p,obs:e.target.value})}/></label></div><div className="filters"><button className="btn green" onClick={()=>salvar(p)}>Salvar</button><button className="btn secondary" onClick={fechar}>Cancelar</button></div></div></div>}
function ClienteDetalhe({nome,itens,fechar}:any){return <div className="modal"><div className="modal-box"><h2>{nome}</h2><p>Detalhamento dos pedidos e valores em aberto.</p><table className="table"><thead><tr><th>Data</th><th>Produto</th><th>Total</th><th>Recebido</th><th>Saldo</th></tr></thead><tbody>{itens.map((p:Pedido)=><tr key={p.id}><td>{p.data}</td><td>{p.produto}</td><td>{brl(p.valor)}</td><td>{brl(p.recebido)}</td><td>{brl(p.valor-p.recebido)}</td></tr>)}</tbody></table><button className="btn" onClick={fechar}>Fechar</button></div></div>}
